---
title: "Silly little pie chart"
format: html
editor: visual
---

```{r}
# Get the Data

# Read in with tidytuesdayR package 
#install.packages("tidytuesdayR")
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2023-06-20')
tuesdata <- tidytuesdayR::tt_load(2023, week = 25)

ufo_sightings <- tuesdata$`ufo_sightings`
places <- tuesdata$`places`
day_parts_map <- tuesdata$`day_parts_map`

# Or read in the data manually

ufo_sightings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/ufo_sightings.csv')
places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/places.csv')
day_parts_map <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-20/day_parts_map.csv')
```

```{r}
library(tidyverse)
library(scales)
library(ggplot2)
library(ggrepel)
```

```{r}
ufo_sightings|>
  select(has_images)|>
  count(has_images)|>
  rbind(c("TRUE", "0"))-> images_df
  
```

```{r}
images_df <-as.data.frame(images_df)
```

```{r}
ggplot(images_df, mapping = aes(x = "",
                                y = as.numeric(n),
                                fill = has_images,
                                ))+
  geom_bar(width = 1,
           stat = "identity",
           )+
  coord_polar("y",
              start = 0)+
  labs(x = "",
       y= "",
       fill = "Has Image(s) of sighting",
       title = "Pics or it Didn't Happen",
       subtitle = "Percent of UFO sightings that have images of the sighting*",
       caption = "Data from Tidy Tuesday June 20th 2023 \n Plot made by Marielle Starret for use by the Gordon College Data Science Practicum 2023\n*note: there is speculation that this data was misrecorded and therefore erroneous")+
  theme_void()+
  theme(plot.background = element_rect(fill = "white"),
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 15, face = "plain"))+
  scale_fill_manual(values = c("steelblue1", "steelblue4"))+
  geom_label_repel(data = images_df,
                   aes(y = percent,
                   label = paste0(percent, "%")),
                   nudge_x = 1,
                   direction = "x", 
                   show.legend = F,
                  ) -> pics_or_it_didnt_happen_plot
```

```{r}
images_df
```

```{r}
images_df|>
  mutate(images_df, n_numeric = as.numeric(n))|>
  mutate(images_df, percent = n_numeric / sum(n_numeric) * 100)-> images_df
```

```{r}
install.packages("ggrepel")
```

```{r}
images_df
```

```{r}
ggsave(plot = pics_or_it_didnt_happen_plot,
       filename = "pics_or_it_didnt_happen_plot.png",
       height = 7,
       width = 8)
```
